bodegas/urls.py
from django.urls import path
from django.views.generic import RedirectView
from bodegas import views as modelViews

bodegas_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.CreateView.as_view(),    name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),    name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',          modelViews.Search,                  name='Search'),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "Bodegas")

inventariosBase/urls.py
from django.contrib import admin
from django.urls import path, include

from codeBackEnd.urls import codeBackEnd_patterns
from inventarios.urls import inventarios_patterns
from categorias.urls import categorias_patterns
from bodegas.urls import bodegas_patterns
from proveedores.urls import proveedores_patterns
from transaccionesInventarios.urls import transaccionesInv_patterns
from usuarios.urls import usuarios_patterns

urlpatterns = [
    path('DJAdmin/', admin.site.urls),

    # Paths del auth
    path('', include('django.contrib.auth.urls')),

    # Paths de Admin
    path('', include(codeBackEnd_patterns)),
    path('usuarios/',        include(usuarios_patterns)),

    path('inventarios/',        include(inventarios_patterns)),
    path('categorias/',         include(categorias_patterns)),
    path('bodegas/',            include(bodegas_patterns)),
    path('proveedores/',        include(proveedores_patterns)),
    path('transaccionesInv/',   include(transaccionesInv_patterns)),
]

transaccionesInventarios/urls.py
from django.urls import path
from django.views.generic import RedirectView
from transaccionesInventarios import views as modelViews

transaccionesInv_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.Add,                     name="Add"),
    path('add/<int:pk>/',   modelViews.AddInventory,            name="AddInventory"),
    path('deduct',          modelViews.Deduce,                  name="Deduct"),
    path('deduct/<int:pk>/',modelViews.DeduceInventory,         name="DeductInventory"),
    path('search',          modelViews.Search,                  name='Search'),
    path('save',            modelViews.SaveTransaction,         name='Save'),
    path('getTransaction',  modelViews.getTransaction,          name='getTransaction'),
    path('<int:pk>',        modelViews.showTransaction,         name="showTransaction"),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "TransaccionesInv")

bodegas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bodegas(models.Model):
    nombre          = models.CharField(max_length=100, verbose_name="Nombre")
    responsable     = models.ForeignKey(User, verbose_name="Responsable de la bodega", on_delete=models.DO_NOTHING)
    observacion     = models.CharField(max_length=155, verbose_name="Observación", default="No indicado")

    def __str__(self):
        return self.nombre

transaccionesInventarios/models.py
from operator import truth
from django.db import models
from django.contrib.auth.models import User
from bodegas.models import Bodegas
from inventarios.models import Productos
from proveedores.models import Proveedores

# Create your models here.
class Transacciones(models.Model):
    responsable = models.ForeignKey(User, verbose_name="Quien realizó el movimiento", on_delete=models.DO_NOTHING)
    fecha       = models.DateTimeField(auto_now_add=True, verbose_name="Fecha del movimiento")
    tipo        = models.BooleanField(verbose_name="Tipo movimiento", default=False)
    bodega      = models.ForeignKey(Bodegas, verbose_name="Bodega", on_delete=models.DO_NOTHING)
    proveedor   = models.ForeignKey(Proveedores, verbose_name="Proveedor del inventario", on_delete=models.DO_NOTHING, default=1)

class Lineas(models.Model):
    transaccion = models.ForeignKey(Transacciones, verbose_name="Transacción a la que pertenece", on_delete=models.DO_NOTHING)
    producto    = models.ForeignKey(Productos, verbose_name="Producto", on_delete=models.DO_NOTHING)
    cantidad    = models.IntegerField(verbose_name="Cantidad registrada", default=0)

transaccionesInventarios/forms.py
from django import forms
from .models import Transacciones

class BaseForm(forms.ModelForm):
    class Meta:
        model = Transacciones
        fields = [
            'responsable',
            'tipo',
            'bodega',
            'proveedor',
        ]

        widgets = {
            'cantidad'      : forms.TextInput(attrs={'class': 'form-control' , 'placeholder': 'Cantidad'}),
        }

class FormEdit(forms.ModelForm):
    class Meta:
        model = Transacciones
        fields = [
            'responsable',
            'tipo',
            'bodega',
            'proveedor',
        ]

transaccionesInventarios/views.py
import json
import io
import xlsxwriter
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse, HttpResponse
from django.db.models import F
from .models import Transacciones, Lineas
from .forms import BaseForm, FormEdit
from bodegas.models import Bodegas
from inventarios.models import Productos
from inventarios import forms as formInventarios
from usuarios.views import consultar_PermisoUsuario
from proveedores.models import Proveedores
from datetime import datetime
from codeBackEnd.funciones import estructuraExcel

# Create your views here.
class baseListView(ListView):
    model = Transacciones
    template_name = 'transaccionesInventarios/List.html'
    paginate_by = 30

    ordering = ['-fecha']

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('codeBackEnd:dashboard')

def Add(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.add_transacciones'):
            bodegas = Bodegas.objects.all()
            datos = {
                'bodegas':bodegas,
                'accion': 1,
            }
            return render(request, "transaccionesInventarios/select_warehouse.html", datos)
        else:
            return redirect('TransaccionesInv:Base')
    else:
        return redirect('login')

def AddInventory(request, pk):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.add_transacciones'):
            bodega = Bodegas.objects.filter(id=pk)[0]
            proveedores = Proveedores.objects.all()
            datos = {
                'bodega':bodega,
                'proveedores':proveedores,
                'accion': 1,
                'formInventario': formInventarios.BaseForm(),
            }
            return render(request, "transaccionesInventarios/Action.html", datos)
        else:
            return redirect('TransaccionesInv:Base')
    else:
        return redirect('login')

def Deduce(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.add_transacciones'):
            bodegas = Bodegas.objects.all()
            datos = {
                'bodegas':bodegas,
                'accion': 0,
            }
            return render(request, "transaccionesInventarios/select_warehouse.html", datos)
        else:
            return redirect('TransaccionesInv:Base')
    else:
        return redirect('login')

def DeduceInventory(request, pk):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.add_transacciones'):
            bodega = Bodegas.objects.filter(id=pk)[0]
            proveedores = Proveedores.objects.all()
            datos = {
                'bodega':bodega,
                'proveedores':proveedores,
                'accion': 0,
                'formInventario': formInventarios.BaseForm(),
            }
            return render(request, "transaccionesInventarios/Action.html", datos)
        else:
            return redirect('TransaccionesInv:Base')
    else:
        return redirect('login')

def Search(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
            ''' Por fecha '''
            fecha_inicio = request.GET.get('fecha_inicio', '')
            fecha_fin = request.GET.get('fecha_fin', '')
            transaccion_fecha = request.GET.get('transaccion_fecha', '')

            ''' Por responsable '''
            responsable = request.GET.get('responsable', '')
            transaccion_resp = request.GET.get('transaccion_resp', '')

            # trae los Transacciones relacionados
            filtro_list = []

            if (fecha_inicio != '' and fecha_inicio != None) and (fecha_fin != '' and fecha_fin != None) and (transaccion_fecha != '' and transaccion_fecha != None):
                ''' invertir fechas '''
                fecha_inicio = fecha_inicio.split('-')
                fecha_inicio = fecha_inicio[2] +'-'+ fecha_inicio[1] +'-'+ fecha_inicio[0]+' 00:00:00'
                fecha_fin = fecha_fin.split('-')
                fecha_fin = fecha_fin[2] +'-'+ fecha_fin[1] +'-'+ fecha_fin[0]+' 23:59:59'

                if ( transaccion_fecha == "2"):
                    filtro_list = Transacciones.objects.filter(
                        fecha__gte=fecha_inicio, fecha__lte=fecha_fin,
                        tipo=1,
                    ).order_by("-fecha")
                elif( transaccion_fecha == "3"):
                    filtro_list = Transacciones.objects.filter(
                        fecha__gte=fecha_inicio, fecha__lte=fecha_fin,
                        tipo=0,
                    ).order_by("-fecha")
                else:
                    filtro_list = Transacciones.objects.filter(fecha__gte=fecha_inicio, fecha__lte=fecha_fin).order_by("-fecha")
            elif (responsable != '' and responsable != None) and (transaccion_resp != '' and transaccion_resp != None):
                if ( transaccion_resp == "2"):
                    filtro_list = Transacciones.objects.filter(
                        responsable=responsable,
                        tipo=1,
                    ).order_by("-fecha")
                elif( transaccion_resp == "3"):
                    filtro_list = Transacciones.objects.filter(
                        responsable=responsable,
                        tipo=0,
                    ).order_by("-fecha")
                else:
                    filtro_list = Transacciones.objects.filter(responsable=responsable).order_by("-fecha")
            else:
                return redirect(reverse_lazy('TransaccionesInv:Base'))

            page = request.GET.get('page', 1)
            paginator = Paginator(filtro_list, 30)

            try:
                categorias = paginator.page(page)
            except PageNotAnInteger:
                categorias = paginator.page(1)
            except EmptyPage:
                categorias = paginator.page(paginator.num_pages)

            datos = {
                'is_paginated':  True if paginator.num_pages > 1 else False,
                'page_obj': categorias,
            }

            return render(request, "transaccionesInventarios/List.html", datos)
        else:
            return redirect('codeBackEnd:dashboard')
    else:
        return redirect('login')

def SaveTransaction(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.add_transacciones'):
            if request.method == 'POST':
                listadoProductos = json.loads(request.POST['listadoProductos'])

                bodega = Bodegas.objects.filter(id=request.POST['idBodega'])[0]
                proveedor = Proveedores.objects.filter(id=request.POST['proveedor'])[0]

                transaccion = Transacciones(
                    responsable= request.user,
                    tipo= request.POST['tipoTransaccion'], # 0: salida, 1: entrada
                    bodega= bodega,
                    proveedor= proveedor,
                )
                transaccion.save()

                for item in listadoProductos["productos"]:
                    # {'codProducto': 'X0030754RP', 'nombre': 'Mouse', 'id': 4, 'cantidad': 1}
                    producto = Productos.objects.filter(codigoProduto=item["codProducto"])[0]

                    linea = Lineas(
                        transaccion = transaccion,
                        producto = producto,
                        cantidad = item["cantidad"],
                    )
                    linea.save()

                    if request.POST['tipoTransaccion'] == "0":
                        Productos.objects.filter(codigoProduto=item["codProducto"]).update(cantidad=F("cantidad") - item["cantidad"])
                    else:
                        Productos.objects.filter(codigoProduto=item["codProducto"]).update(cantidad=F("cantidad") + item["cantidad"])

                # Redireccionar a listado de transacciones
                return redirect('TransaccionesInv:Base')
            else:
                return JsonResponse({ "error": True, "msj": "Method not allowed" })
        else:
            return redirect('TransaccionesInv:Base')
    else:
        return redirect('login')

def getTransaction(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            filtroId = request.POST['idTransaccion']

            if filtroId != '':
                try:
                    transaccion = Transacciones.objects.filter(id=filtroId)[0]
                except Transacciones.DoesNotExist:
                    return JsonResponse({"error": True, "existe": 0})

                lineas = Lineas.objects.filter(transaccion=transaccion.id)

                lineasTransaccion = {}

                contador = 0
                for linea in lineas:
                    lineaTransaccion = {
                        'producto': {
                            'nombre': linea.producto.nombre,
                            'cantidad': linea.producto.cantidad,

transaccionesInventarios/templates/transaccionesInventarios/Action.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% load inventarios_extras %}
{% block title %}
    {% if accion == 1 %}
        Generar entrada de inventario en {{bodega}}
    {% else %}
        Generar salida de inventario en {{bodega}}
    {% endif %}
{% endblock %}
{% block tituloSeccion %}
    {% if accion == 1 %}
        <img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/import.png' %}"> Generar entrada de inventario en <b>{{bodega}}</b>
    {% else %}
        <img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/export.png' %}"> Generar salida de inventario en <b>{{bodega}}</b>
    {% endif %}
{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        .numCantidad{
            font-weight: bold;
            font-size: 16px !important;
        }
        .mensajeRemove{
            font-size: 17px;
        }
        #id_descripcion{
            height: 100px !important;
            resize: none;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="{% url 'TransaccionesInv:Save' %}" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-12">
            <label for="id_nombre">Código del producto:</label>
            <input type="text" id="codProducto" placeholder="Escanee o digite el código del producto" class="form-control" autofocus id="id_nombre" autocomplete="off">
            <div class="card-category estado estado-producto">
                <div class="alert alert-danger" role="alert" id="ErrorCodigo" style="display:none;">
                    <span id="mensajeErrorCodigo"></span>
                </div>
            </div>
        </div>
        
        <table class="display table table-striped table-hover" id="dataTable">
            <thead>
                <tr>
                    <th style="text-align: center;">Producto</th>
                    <th style="text-align: center;">Cantidad</th>
                    <th style="text-align: center;">
                        <a href="#" title="Haga clic sobre el icono para editar la fila."><i class='fa fa-info text-white'></i></a>
                    </th>
                </tr>
            </thead>
            <tbody id="tablaProductos">
                <tr>
                    <td colspan="3" class="text-center">
                        Escanee o digite el código del producto para agregar líneas
                    </td>
                </tr>
            </tbody>
        </table>


        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    {% if accion == 1 %}
                        <a href="{% url 'TransaccionesInv:Add' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver a seleccion de bodega</a>
                    {% else %}
                        <a href="{% url 'TransaccionesInv:Deduct' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver a seleccion de bodega</a>
                    {% endif %}
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button id="emitirTransaccion" type="button" class="btn btn-light" style="display: none;">
                        {% if accion == 1 %}
                            <i class="far fa-save"></i> Registrar entrada de inventario
                        {% else %}
                            <i class="far fa-save"></i> Registrar salida de inventario
                        {% endif %}
                    </button>
                </div>
            </div>
        </div>


        <input type="hidden" name="tipoTransaccion" value="{{accion}}" />
        <input type="hidden" name="idBodega" value="{{bodega.id}}" />
        <textarea id="listadoProductos" name="listadoProductos" style="width: 100%; height: 90px; display: none;">{"productos":[]}</textarea>

        <div class="modal fade" id="seleccionProveedor" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-body">
                        <div class="form-group col-md-12">
                            <label for="id_proveedor">Proveedor del inventario del movimiento:</label>
                            <select id="id_proveedor" name="proveedor" class="selectpicker w-100" required>
                                {% for linea in proveedores %}
                                    <option value="{{ linea.id }}">{{ linea.nombre }}</option> 
                                {% endfor%}
                            </select>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group col-md-12 pr-0">
                            <div class="row col-md-12 pr-0">
                                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                                    <button type="button" class="btn btn-light" data-dismiss="modal"><i class="fas fa-chevron-left"></i> Cerrar</button>
                                </div>
                                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                                    <button type="submit" class="btn btn-light">
                                        {% if accion == 1 %}
                                            <i class="far fa-save"></i> Registrar entrada de inventario
                                        {% else %}
                                            <i class="far fa-save"></i> Registrar salida de inventario
                                        {% endif %}
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="modal fade" id="RemoveModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body" id="RemoveContent"></div>
                <div class="modal-footer" id="RemoveBotones"></div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modalAddInventario" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="javascript: agregarProducto()" id="formAddInventario" method="post" enctype="multipart/form-data" class="row ">
                        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
                            <div class="card-category estado estado-producto">
                                <div class="alert alert-info py-2 my-2" role="alert">
                                    <span style="font-size: 17px;">El producto no existe, ¿desea crear el nuevo producto?</span>
                                </div>
                            </div>
                        </div>

                        <div class="form-group col-md-6"> {% comment %} nombre {% endcomment %}
                            {{ formInventario.nombre.label_tag }}
                            {{ formInventario.nombre }}
                            {{ formInventario.nombre.errors }}
                        </div>

                        <div class="form-group col-md-6"> {% comment %} cantidad {% endcomment %}
                            <label for="id_cantidad">Cantidad de existencias:</label>
                            {{ formInventario.cantidad }}
                            {{ formInventario.cantidad.errors }}
                        </div>

                        <div class="form-group col-md-6"> {% comment %} codigoProduto {% endcomment %}
                            {{ formInventario.codigoProduto.label_tag }}
                            {{ formInventario.codigoProduto }}
                            {{ formInventario.codigoProduto.errors }}
                        </div>

                        <div class="form-group col-md-6"> {% comment %} categoria {% endcomment %}
                            {{ formInventario.categoria.label_tag }}
                            <div class="selectgroup w-100">
                                <select id="id_categoria" name="categoria" class="selectpicker w-100" multiple data-live-search="true">
                                    {% get_Categorias_list as categorias %}
                                    {% for categoria in categorias %}
                                        <option value="{{ categoria.id }}">{{ categoria.nombre }}</option> 
                                    {% endfor%}
                                </select>
                            </div>
                            {{ formInventario.categoria.errors }}
                        </div>

                        <div class="form-group col-md-12"> {% comment %} descripcion {% endcomment %}
                            {{ formInventario.descripcion.label_tag }}
                            {{ formInventario.descripcion }}
                            {{ formInventario.descripcion.errors }}
                        </div>

                        <div class="form-group col-md-12 pr-0">
                            <div class="row col-md-12 pr-0">
                                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                                    <button type="button" class="btn btn-light" data-dismiss="modal"><i class="fas fa-chevron-left"></i> Cerrar</button>
                                </div>
                                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                                    <button type="submit" class="btn btn-light">
                                        <i class="far fa-save"></i> Guardar producto
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customJs %}
    <script src="{% static 'transaccionesInventarios/assets/js/validar.js' %}"></script>
    <script src="{% static 'transaccionesInventarios/assets/js/process.js' %}"></script>
    <script>
    </script>
{% endblock %}

transaccionesInventarios/templates/transaccionesInventarios/Deduct.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% block title %}Transacciones de inventarios{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/check-list.png' %}"> Transacciones de inventarios{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style></style>
{% endblock %}

{% block content %}
    <form action="" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Categorias:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar categoría
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block customJs %}
    <script src="{% static 'categorias/assets/js/validar.js' %}"></script>
{% endblock %}

transaccionesInventarios/templates/transaccionesInventarios/select_warehouse.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% load codeBackEnd_extras %}
{% block title %}Transacciones de inventarios{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/checklists.png' %}"> Selección de bodega{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        .customCard{
            background: rgba(0,0,0,.2) !important;
        }

        .icono-card{
            background: #00193A;
            border-radius: 4px;
        }

        .card-stats{
            background: rgba(0,0,0,0.2) !important;
        }
        .card-stats:hover{
            background: rgba(0,0,0,0.4) !important;
            text-decoration: none;
        }

        @media(max-width: 575px){
            .card-stats .col-stats {
                display: block !important;
            }
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12 row row-card-no-pd">

            {% for bodega in bodegas %}
                <div class="col-12 col-sm-6 col-md-6 mb-2">
                    {% if accion == 1 %}
                    <a class="card card-stats card-round" href="{% url 'TransaccionesInv:AddInventory' pk=bodega.id %}">
                    {% else %}
                    <a class="card card-stats card-round" href="{% url 'TransaccionesInv:DeductInventory' pk=bodega.id %}">
                    {% endif %}
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-sm-5">
                                    <div class="icon-big text-center icono-card">
                                        <img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/inventory.png' %}">
                                    </div>
                                </div>
                                <div class="col-sm-7 col-stats">
                                    <div class="numbers">
                                        <h4 class="card-title text-justify">{{bodega.nombre}}</h4>
                                        <p class="text-justify text-white">{{bodega.observacion}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
        
        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'TransaccionesInv:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customJs %}
    <script>
    </script>
{% endblock %}