bodegas/urls.py
from django.urls import path
from django.views.generic import RedirectView
from bodegas import views as modelViews

bodegas_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.CreateView.as_view(),    name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),    name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',          modelViews.Search,                  name='Search'),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "Bodegas")

inventariosBase/urls.py
from django.contrib import admin
from django.urls import path, include

from codeBackEnd.urls import codeBackEnd_patterns
from inventarios.urls import inventarios_patterns
from categorias.urls import categorias_patterns
from bodegas.urls import bodegas_patterns
from proveedores.urls import proveedores_patterns
from transaccionesInventarios.urls import transaccionesInv_patterns
from usuarios.urls import usuarios_patterns

urlpatterns = [
    path('DJAdmin/', admin.site.urls),

    # Paths del auth
    path('', include('django.contrib.auth.urls')),

    # Paths de Admin
    path('', include(codeBackEnd_patterns)),
    path('usuarios/',        include(usuarios_patterns)),

    path('inventarios/',        include(inventarios_patterns)),
    path('categorias/',         include(categorias_patterns)),
    path('bodegas/',            include(bodegas_patterns)),
    path('proveedores/',        include(proveedores_patterns)),
    path('transaccionesInv/',   include(transaccionesInv_patterns)),
]

bodegas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bodegas(models.Model):
    nombre          = models.CharField(max_length=100, verbose_name="Nombre")
    responsable     = models.ForeignKey(User, verbose_name="Responsable de la bodega", on_delete=models.DO_NOTHING)
    observacion     = models.CharField(max_length=155, verbose_name="Observación", default="No indicado")

    def __str__(self):
        return self.nombre

bodegas/forms.py
from django import forms
from .models import Bodegas

class BaseForm(forms.ModelForm):
    class Meta:
        model = Bodegas
        fields = [
            'nombre',
            'responsable',
            'observacion',
        ]

        widgets = {
            'nombre'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'observacion'   : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Observación', 'required': 'true'}),
        }

class FormEdit(forms.ModelForm):
    class Meta:
        model = Bodegas
        fields = [
            'nombre',
            'responsable',
            'observacion',
        ]

        widgets = {
            'nombre'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'observacion'   : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Observación', 'required': 'true'}),
        }

bodegas/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy, reverse
from .models import Bodegas
from .forms import BaseForm, FormEdit
from usuarios.views import consultar_PermisoUsuario
from codeBackEnd.funciones import estructuraExcel

# Create your views here.
class baseListView(ListView):
    model = Bodegas
    template_name = 'bodegas/List.html'
    paginate_by = 30

    ordering = ['-nombre']

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'bodegas.view_bodegas'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('codeBackEnd:dashboard')

class DeleteView(DeleteView):
    model = Bodegas
    template_name = 'bodegas/Del.html'
    success_url = reverse_lazy('Bodegas:Base')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'bodegas.delete_bodegas'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Bodegas:Base')

class CreateView(CreateView):
    model = Bodegas
    form_class = BaseForm
    template_name = 'bodegas/Add.html'
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'bodegas.add_bodegas'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Bodegas:Base')

    def get_success_url(self):
        # return reverse_lazy('comercioAdmin:producto', kwargs={ 'pk': self.object.id })
        return reverse_lazy('Bodegas:Base') + '?created'

class UpdateView(UpdateView):
    model = Bodegas
    form_class = FormEdit
    template_name = 'bodegas/Edit.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'bodegas.change_bodegas'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Bodegas:Base')

    def get_success_url(self):
        return reverse_lazy('Bodegas:Edit', args=[self.object.id]) + '?updated'

def Search(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'bodegas.view_bodegas'):
            filtroNombre = request.GET.get('nombre', '')
            filtroResponsable = request.GET.get('responsable', '')

            # trae los Bodegas relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Bodegas.objects.filter(nombre__icontains=filtroNombre)
            elif filtroResponsable != '' and filtroResponsable != None:
                filtro_list = Bodegas.objects.filter(responsable=filtroResponsable)
            else:
                return redirect(reverse_lazy('Bodegas:Base'))

            page = request.GET.get('page', 1)
            paginator = Paginator(filtro_list, 30)

            try:
                bodegas = paginator.page(page)
            except PageNotAnInteger:
                bodegas = paginator.page(1)
            except EmptyPage:
                bodegas = paginator.page(paginator.num_pages)

            datos = {
                'is_paginated':  True if paginator.num_pages > 1 else False,
                'page_obj': bodegas,
            }

            return render(request, "bodegas/List.html", datos)
        else:
            return redirect('codeBackEnd:dashboard')
    else:
        return redirect('login')

def exportExcel(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
            filtroNombre = request.GET.get('nombre', '')
            filtroResponsable = request.GET.get('responsable', '')

            # trae los Bodegas relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Bodegas.objects.filter(nombre__icontains=filtroNombre)
            elif filtroResponsable != '' and filtroResponsable != None:
                filtro_list = Bodegas.objects.filter(responsable=filtroResponsable)
            else:
                filtro_list = Bodegas.objects.all()

            datosExcel = []

            for bodega in filtro_list:

                linea = [[
                    bodega.id,
                    bodega.nombre,
                    bodega.responsable.first_name+' '+bodega.responsable.last_name,
                    bodega.observacion,
                ]]
                datosExcel = datosExcel + linea

            titulos = [[
                "N. Bodegas",
                "Nombre",
                "Responsable",
                "Observacion",
            ],]

            excelExportar = estructuraExcel(titulos, datosExcel, 'bodegas')

            # return the response
            return excelExportar
        else:
            return redirect('codeBackEnd:dashboard')

    else:
        return redirect('login')

bodegas/templates/bodegas/Add.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% load bodegas_extras %}
{% load codeBackEnd_extras %}
{% load usuarios_extras %}
{% block title %}Nueva bodega{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/inventory.png' %}"> Nueva bodega{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style></style>
{% endblock %}

{% block content %}
    <form action="" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-6"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} responsable {% endcomment %}
            {{ form.responsable.label_tag }}
            <div class="selectgroup w-100">
                <select id="id_responsable" name="responsable" class="selectpicker w-100" data-live-search="true">
                    {% get_Usuarios_list as usuarios %}
                    {% for usuario in usuarios %}
                        <option value="{{ usuario.id }}">{{ usuario.first_name }} {{ usuario.last_name }}</option> 
                    {% endfor%}
                </select>
            </div>
            {{ form.responsable.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} observacion {% endcomment %}
            {{ form.observacion.label_tag }}
            {{ form.observacion }}
            {{ form.observacion.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Bodegas:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar categoría
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block customJs %}
    <script src="{% static 'bodegas/assets/js/validar.js' %}"></script>
{% endblock %}

bodegas/templates/bodegas/Del.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Borrar bodega{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/inventory.png' %}"> Borrar bodega{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        tbody tr td{ color: #ffffff; }
        tbody tr td a{ color: #5C9FF1; padding-left: 10px; }
        .estado .alert{
            background-color: rgba(255,255,255,.05);
            margin-top: 10px;
            padding: .8rem 1rem;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <h2 class="text-white">¿Estás seguro de que quieres borrar "<b>{{ object }}</b>"?</h2>
        <input type="submit"  class="btn btn-danger float-right" value="Sí, borrar" />
    </form>
{% endblock %}

bodegas/templates/bodegas/Edit.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% load bodegas_extras %}
{% load codeBackEnd_extras %}
{% load usuarios_extras %}
{% block title %}Editar bodega{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/inventory.png' %}"> Editar bodega{% endblock %}

{% block customCss %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <form action="" id="formEdit" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-6"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-6"> {% comment %} responsable {% endcomment %}
            {{ form.responsable.label_tag }}
            <div class="selectgroup w-100">
                <select id="id_responsable" name="responsable" class="selectpicker w-100" data-live-search="true">
                    {% get_Usuarios_list as usuarios %}
                    {% for usuario in usuarios %}
                        {% if usuario.id == form.responsable.value %}
                            <option value="{{ usuario.id }}" selected>{{ usuario.first_name }} {{ usuario.last_name }}</option>
                        {% else %}
                            <option value="{{ usuario.id }}">{{ usuario.first_name }} {{ usuario.last_name }}</option>
                        {% endif %}
                    {% endfor%}
                </select>
            </div>
            {{ form.responsable.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} observacion {% endcomment %}
            {{ form.observacion.label_tag }}
            {{ form.observacion }}
            {{ form.observacion.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Bodegas:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar cambios
                    </button>
                </div>
            </div>
        </div>
    </form>

{% endblock %}

{% block customJs %}
    <script src="{% static 'bodegas/assets/js/validar.js' %}"></script>
    <script>
        {% if 'updated' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha actualizado la categoría",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}
    </script>
{% endblock %}

bodegas/templates/bodegas/List.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% load codeBackEnd_extras %}
{% load usuarios_extras %}
{% load usuarios_extras %}
{% block title %}Bodegas{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/inventory.png' %}"> Bodegas disponibles{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <div class="col-md-12 p-0">
        {% get_PermisoUsuario request.user.id "bodegas.add_bodegas" as Permiso %}

        {% if 'nombre' not in request.GET and 'responsable'  not in request.GET %}
            <form action="{% url 'Bodegas:exportExcel' %}">
                {% if Permiso %}
                    <a href="{% url 'Bodegas:Add' %}" type="button" class="btn btn-light mb-3"><i class="fas fa-plus text-success"></i> Agregar categoría</a>
                {% endif %}

                <button type="button" class="btn btn-light mb-3 ml-1" data-toggle="modal" data-target="#searchModal">
                    <i class="fas fa-search text-info"></i> Buscar
                </button>

                <button type="submit" class="btn btn-light mb-3 ml-1 text-green">
                    <i class="fas fa-solid fa-file-excel color-excel"></i> Exportar Excel
                </button>
            </form>
        {% endif %}
        
        {% if 'nombre' in request.GET or 'responsable' in request.GET %}
            <form action="{% url 'Bodegas:exportExcel' %}">
                {% if Permiso %}
                    <a href="{% url 'Bodegas:Add' %}" type="button" class="btn btn-light mb-3"><i class="fas fa-plus text-success"></i> Agregar categoría</a>
                {% endif %}

                <button type="button" class="btn btn-light mb-3 ml-1" data-toggle="modal" data-target="#searchModal">
                    <i class="fas fa-search text-info"></i> Buscar
                </button>

                <a href="{% url 'Bodegas:Base' %}" type="button" class="btn btn-light mb-3 ml-1"><i class="fas fa-eraser text-danger"></i> Quitar búsqueda</a>

                {% if 'nombre' in request.GET %}
                    <input type="hidden" name="nombre" value="{{request.GET.nombre}}">
                {% endif %}

                {% if 'responsable' in request.GET %}
                    <input type="hidden" name="responsable" value="{{request.GET.responsable}}">
                {% endif %}

                <button type="submit" class="btn btn-light mb-3 ml-1">
                    <i class="fas fa-solid fa-file-excel color-excel"></i> Exportar Excel
                </button>
            </form>
        {% endif %}
    </div>

    {% if 'nombre' in request.GET %}
    <div class="col-md-12 p-0 my-3 text-white">
        <h3>
            {% if 'nombre' in request.GET %}
                Buscando por nombre: <b>{{request.GET.nombre}}</b>
            {% endif %}
        </h3>
    </div>
    {% endif %}

    <div class="table-responsive">
        {% if page_obj|length == 0 %}
            <div class="card-category estado estado-producto">
                <div class="alert alert-danger" role="alert">
                    <span>No hay datos para mostrar</span>
                </div>
            </div>
        {% else %}
            <table class="display table table-striped table-hover" id="dataTable">
                <thead>
                    <tr>
                        <th style="text-align: center;">Nombre</th>
                        <th style="text-align: center;">Responsable</th>
                        <th style="text-align: center;">Observación</th>
                        {% get_PermisoUsuario request.user.id "bodegas.change_bodegas" as Permiso %}
                        {% if Permiso %}
                            <th style="text-align: center;">
                                <a href="#" title="Haga clic sobre el icono para editar la fila."><i class='fa fa-info text-white'></i></a>
                            </th>
                        {% endif %}
                        {% comment %} <th style="text-align: center;">
                            <a href="#" title="Haga clic sobre el icono para eliminar la fila."><i class='fa fa-info'></i></a>
                        </th> {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                    {% for linea in page_obj %}
                        <tr>
                            <td style="text-align: center;">{{ linea.nombre }}</td>
                            <td style="text-align: center;">{{linea.responsable.first_name}} {{ linea.responsable.last_name }}</td>
                            <td>{{ linea.observacion }}</td>
                            {% get_PermisoUsuario request.user.id "bodegas.change_bodegas" as Permiso %}
                            {% if Permiso %}
                                <td style="text-align: center;"><a href="{% url 'Bodegas:Edit' pk=linea.id %}" class="btn btn-primary"><i class="fas fa-pencil-alt fa-lg"></i> Editar</a></td>
                            {% endif %}
                            {% comment %} <td style="text-align: center;"><a href="{% url 'Bodegas:Delete' pk=linea.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i> Borrar</a></td> {% endcomment %}
                        </tr>
                    {% endfor%}
                </tbody>
            </table>

            {% if is_paginated %}
                <div class="d-flex justify-content-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                {% if 'nombre' in request.GET %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page=1&name={{ request.GET.name }}">Primera</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&name={{ request.GET.name }}"><</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page=1">Primera</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a></li>
                                {% endif %}
                            {% endif %}

                            {% for i in page_obj.paginator.page_range %}
                                
                                <li class="page-item">
                                    {% if request.GET.page|to_int == i|to_int %}
                                        {% if 'nombre' in request.GET %}
                                            <a class="page-link page-selected" href="?page={{ i }}&name={{ request.GET.name }}">{{ i }}</a>
                                        {% else %}
                                            <a class="page-link page-selected" href="?page={{ i }}">{{ i }}</a>
                                        {% endif %}
                                    {% else %}
                                        {% if 'nombre' in request.GET %}
                                            <a class="page-link" href="?page={{ i }}&name={{ request.GET.name }}">{{ i }}</a>
                                        {% else %}
                                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                        {% endif %}
                                    {% endif %}
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                {% if 'nombre' in request.GET %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&name={{ request.GET.name }}">></a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&name={{ request.GET.name }}">Última</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">></a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última</a></li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            {% endif %}

        {% endif %}
    </div>

    <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="{% url 'Bodegas:Search' %}" id="formSearchName" method="get" enctype="multipart/form-data" class="row ">
                        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
                            <label for="id_nombre">Nombre:</label>
                            {% if 'nombre' in request.GET %}
                                <input type="text" name="nombre" class="form-control" placeholder="Nombre" maxlength="100" required="" value="{{request.GET.nombre}}">
                            {% else %}
                                <input type="text" name="nombre" class="form-control" placeholder="Nombre" maxlength="100" required="">
                            {% endif %}
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-light">
                                <i class="fas fa-search text-info"></i> Buscar por nombre
                            </button>
                        </div>
                    </form>

                    <form action="{% url 'Bodegas:Search' %}" method="get" enctype="multipart/form-data" class="row ">
                        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
                            <label for="id_nombre">Responsable:</label>
                            <div class="selectgroup w-100">
                                <select id="id_responsable" name="responsable" class="selectpicker w-100" data-live-search="true">
                                    {% get_Usuarios_list as usuarios %}
                                    {% for usuario in usuarios %}
                                        {% if 'responsable' in request.GET %}
                                            {% if usuario.id|to_int == request.GET.responsable|to_int %}
                                                <option value="{{ usuario.id }}" selected>{{ usuario.first_name }} {{ usuario.last_name }}</option>
                                            {% else %}
                                                <option value="{{ usuario.id }}">{{ usuario.first_name }} {{ usuario.last_name }}</option>
                                            {% endif %}
                                        {% else %}
                                            <option value="{{ usuario.id }}">{{ usuario.first_name }} {{ usuario.last_name }}</option>
                                        {% endif %}
                                    {% endfor%}
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-light">
                                <i class="fas fa-search text-info"></i> Buscar por responsable
                            </button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customJs %}
    <script src="{% static 'bodegas/assets/js/validar.js' %}"></script>
    <script>
        {% if 'created' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha creado la categoría",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}
    </script>
{% endblock %}