bodegas/urls.py
from django.urls import path
from django.views.generic import RedirectView
from bodegas import views as modelViews

bodegas_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.CreateView.as_view(),    name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),    name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',          modelViews.Search,                  name='Search'),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "Bodegas")

inventariosBase/urls.py
from django.contrib import admin
from django.urls import path, include

from codeBackEnd.urls import codeBackEnd_patterns
from inventarios.urls import inventarios_patterns
from categorias.urls import categorias_patterns
from bodegas.urls import bodegas_patterns
from proveedores.urls import proveedores_patterns
from transaccionesInventarios.urls import transaccionesInv_patterns
from usuarios.urls import usuarios_patterns

urlpatterns = [
    path('DJAdmin/', admin.site.urls),

    # Paths del auth
    path('', include('django.contrib.auth.urls')),

    # Paths de Admin
    path('', include(codeBackEnd_patterns)),
    path('usuarios/',        include(usuarios_patterns)),

    path('inventarios/',        include(inventarios_patterns)),
    path('categorias/',         include(categorias_patterns)),
    path('bodegas/',            include(bodegas_patterns)),
    path('proveedores/',        include(proveedores_patterns)),
    path('transaccionesInv/',   include(transaccionesInv_patterns)),
]

proveedores/urls.py
from django.urls import path
from django.views.generic import RedirectView
from proveedores import views as modelViews

proveedores_patterns = ([
    path('',                modelViews.baseListView.as_view(),name="Base"),
    path('add',             modelViews.CreateView.as_view(),  name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),  name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),  name="Delete"),
    path('search',          modelViews.Search,                name='Search'),
    path('export',          modelViews.exportExcel,           name="exportExcel"),
], "Proveedores")

proveedores/models.py
from django.db import models

# Create your models here.
class Proveedores(models.Model):
    nombre          = models.CharField(max_length=100, verbose_name="Nombre")
    identificacion  = models.BigIntegerField(verbose_name="Número de identificación")
    email           = models.CharField(max_length=155, verbose_name="Correo electrónico")
    direccion       = models.CharField(max_length=155, verbose_name="Dirección del proveedor")
    contacto        = models.CharField(max_length=100, verbose_name="Nombre de la persona de contácto")
    telefono        = models.IntegerField(verbose_name="Teléfono")
    observacion     = models.CharField(max_length=155, verbose_name="Observación", default="No indicado")

    def __str__(self):
        return self.nombre

proveedores/forms.py
from django import forms
from .models import Proveedores

class BaseForm(forms.ModelForm):
    class Meta:
        model = Proveedores
        fields = [
            'nombre',
            'identificacion',
            'email',
            'direccion',
            'contacto',
            'telefono',
            'observacion',
        ]

        widgets = {
            'nombre'            : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'identificacion'    : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número de identificación'}),
            'email'             : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
            'direccion'         : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección del proveedor'}),
            'contacto'          : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la persona de contácto'}),
            'telefono'          : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Teléfono'}),
            'observacion'       : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Observación', 'required': 'true'}),
        }

class FormEdit(forms.ModelForm):
    class Meta:
        model = Proveedores
        fields = [
            'nombre',
            'identificacion',
            'email',
            'direccion',
            'contacto',
            'telefono',
            'observacion',
        ]

        widgets = {
            'nombre'            : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'identificacion'    : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Número de identificación'}),
            'email'             : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Correo electrónico'}),
            'direccion'         : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Dirección del proveedor'}),
            'contacto'          : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de la persona de contácto'}),
            'telefono'          : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Teléfono'}),
            'observacion'       : forms.Textarea(attrs={'class': 'form-control' , 'placeholder': 'Observación', 'required': 'true'}),
        }

proveedores/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy, reverse
from .models import Proveedores
from .forms import BaseForm, FormEdit
from usuarios.views import consultar_PermisoUsuario
from codeBackEnd.funciones import estructuraExcel

# Create your views here.
class baseListView(ListView):
    model = Proveedores
    template_name = 'proveedores/List.html'
    paginate_by = 30

    ordering = ['-nombre']

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'proveedores.view_proveedores'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('codeBackEnd:dashboard')

class DeleteView(DeleteView):
    model = Proveedores
    template_name = 'proveedores/Del.html'
    success_url = reverse_lazy('Proveedores:Base')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'proveedores.delete_proveedores'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Proveedores:Base')

class CreateView(CreateView):
    model = Proveedores
    form_class = BaseForm
    template_name = 'proveedores/Add.html'
    
    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'proveedores.add_proveedores'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Proveedores:Base')

    def get_success_url(self):
        return reverse_lazy('Proveedores:Base') + '?created'

class UpdateView(UpdateView):
    model = Proveedores
    form_class = FormEdit
    template_name = 'proveedores/Edit.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'proveedores.change_proveedores'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Proveedores:Base')

    def get_success_url(self):
        return reverse_lazy('Proveedores:Edit', args=[self.object.id]) + '?updated'

def Search(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'proveedores.view_proveedores'):
            filtroNombre = request.GET.get('nombre', '')
            filtroIdentificacion = request.GET.get('identificacion', '')

            # trae los Proveedores relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Proveedores.objects.filter(nombre__icontains=filtroNombre)
            elif filtroIdentificacion != '' and filtroIdentificacion != None:
                filtro_list = Proveedores.objects.filter(identificacion__icontains=filtroIdentificacion)
            else:
                return redirect(reverse_lazy('Proveedores:Base'))

            page = request.GET.get('page', 1)
            paginator = Paginator(filtro_list, 30)

            try:
                proveedores = paginator.page(page)
            except PageNotAnInteger:
                proveedores = paginator.page(1)
            except EmptyPage:
                proveedores = paginator.page(paginator.num_pages)

            datos = {
                'is_paginated':  True if paginator.num_pages > 1 else False,
                'page_obj': proveedores,
            }

            return render(request, "proveedores/List.html", datos)
        else:
            return redirect('codeBackEnd:dashboard')
    else:
        return redirect('login')

def exportExcel(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
            filtroNombre = request.GET.get('nombre', '')
            filtroIdentificacion = request.GET.get('identificacion', '')

            # trae los Transacciones relacionados
            filtro_list = []

            if filtroNombre != '' and filtroNombre != None:
                filtro_list = Proveedores.objects.filter(nombre__icontains=filtroNombre)
            elif filtroIdentificacion != '' and filtroIdentificacion != None:
                filtro_list = Proveedores.objects.filter(identificacion__icontains=filtroIdentificacion)
            else:
                filtro_list = Proveedores.objects.all()

            datosExcel = []

            for proveedor in filtro_list:

                linea = [[
                    proveedor.id,
                    proveedor.nombre,
                    proveedor.identificacion,
                    proveedor.email,
                    proveedor.direccion,
                    proveedor.contacto,
                    proveedor.telefono,
                    proveedor.observacion,
                ]]
                datosExcel = datosExcel + linea

            titulos = [[
                "N. Proveedor",
                "Nombre",
                "Identificación",
                "Correo Electrónico",
                "Dirección",
                "Contacto",
                "Teléfono",
                "Observación",
            ],]

            excelExportar = estructuraExcel(titulos, datosExcel, 'proveedores')

            # return the response
            return excelExportar
        else:
            return redirect('codeBackEnd:dashboard')

    else:
        return redirect('login')

proveedores/templates/proveedores/Add.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% block title %}Nuevo proveedor{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/shop.png' %}"> Nuevo proveedor{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style></style>
{% endblock %}

{% block content %}
    <form action="" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
            {{ form.nombre.label_tag }}
            {{ form.nombre }}
            {{ form.nombre.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} identificacion {% endcomment %}
            {{ form.identificacion.label_tag }}
            {{ form.identificacion }}
            {{ form.identificacion.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} email {% endcomment %}
            {{ form.email.label_tag }}
            {{ form.email }}
            {{ form.email.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} direccion {% endcomment %}
            {{ form.direccion.label_tag }}
            {{ form.direccion }}
            {{ form.direccion.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} contacto {% endcomment %}
            {{ form.contacto.label_tag }}
            {{ form.contacto }}
            {{ form.contacto.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} telefono {% endcomment %}
            {{ form.telefono.label_tag }}
            {{ form.telefono }}
            {{ form.telefono.errors }}
        </div>

        <div class="form-group col-md-12"> {% comment %} observacion {% endcomment %}
            {{ form.observacion.label_tag }}
            {{ form.observacion }}
            {{ form.observacion.errors }}
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Proveedores:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar proveedor
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block customJs %}
    <script src="{% static 'proveedores/assets/js/validar.js' %}"></script>
{% endblock %}

proveedores/templates/proveedores/Del.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Borrar proveedor{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/shop.png' %}"> Borrar proveedor{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        tbody tr td{ color: #ffffff; }
        tbody tr td a{ color: #5C9FF1; padding-left: 10px; }
        .estado .alert{
            background-color: rgba(255,255,255,.05);
            margin-top: 10px;
            padding: .8rem 1rem;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <h2 class="text-white">¿Estás seguro de que quieres borrar "<b>{{ object }}</b>"?</h2>
        <input type="submit"  class="btn btn-danger float-right" value="Sí, borrar" />
    </form>
{% endblock %}

proveedores/templates/proveedores/List.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% load codeBackEnd_extras %}
{% load usuarios_extras %}
{% block title %}Proveedores{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/shop.png' %}"> Proveedores disponibles{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
    </style>
{% endblock %}

{% block content %}
    <div class="col-md-12 p-0">
        {% get_PermisoUsuario request.user.id "proveedores.add_proveedores" as Permiso %}
        
        {% if 'nombre' not in request.GET and 'identificacion'  not in request.GET %}
            <form action="{% url 'Proveedores:exportExcel' %}">
                {% if Permiso %}
                    <a href="{% url 'Proveedores:Add' %}" type="button" class="btn btn-light mb-3"><i class="fas fa-plus text-success"></i> Agregar proveedor</a>
                {% endif %}

                <button type="button" class="btn btn-light mb-3 ml-1" data-toggle="modal" data-target="#searchModal">
                    <i class="fas fa-search text-info"></i> Buscar
                </button>

                <button type="submit" class="btn btn-light mb-3 ml-1 text-green">
                    <i class="fas fa-solid fa-file-excel color-excel"></i> Exportar Excel
                </button>
            </form>
        {% endif %}
        
        {% if 'nombre' in request.GET or 'identificacion' in request.GET %}
            <form action="{% url 'Proveedores:exportExcel' %}">
                {% if Permiso %}
                    <a href="{% url 'Proveedores:Add' %}" type="button" class="btn btn-light mb-3"><i class="fas fa-plus text-success"></i> Agregar proveedor</a>
                {% endif %}

                <button type="button" class="btn btn-light mb-3 ml-1" data-toggle="modal" data-target="#searchModal">
                    <i class="fas fa-search text-info"></i> Buscar
                </button>

                <a href="{% url 'Proveedores:Base' %}" type="button" class="btn btn-light mb-3 ml-1"><i class="fas fa-eraser text-danger"></i> Quitar búsqueda</a>

                {% if 'nombre' in request.GET %}
                    <input type="hidden" name="nombre" value="{{request.GET.nombre}}">
                {% endif %}

                {% if 'identificacion' in request.GET %}
                    <input type="hidden" name="identificacion" value="{{request.GET.identificacion}}">
                {% endif %}

                <button type="submit" class="btn btn-light mb-3 ml-1">
                    <i class="fas fa-solid fa-file-excel color-excel"></i> Exportar Excel
                </button>
            </form>
        {% endif %}
    </div>

    {% if 'nombre' in request.GET or 'identificacion' in request.GET %}
    <div class="col-md-12 p-0 my-3 text-white">
        <h3>
            {% if 'nombre' in request.GET %}
                Buscando por nombre: <b>{{request.GET.nombre}}</b>
            {% elif 'identificacion' in request.GET %}
                Buscando por identificación: <b>{{request.GET.identificacion}}</b>
            {% endif %}
        </h3>
    </div>
    {% endif %}

    <div class="table-responsive">
        {% if page_obj|length == 0 %}
            <div class="card-category estado estado-producto">
                <div class="alert alert-danger" role="alert">
                    <span>No hay datos para mostrar</span>
                </div>
            </div>
        {% else %}
            <table class="display table table-striped table-hover" id="dataTable">
                <thead>
                    <tr>
                        <th style="text-align: center;">Nombre</th>
                        <th style="text-align: center;">Identificación</th>
                        <th style="text-align: center;">Correo electrónico</th>
                        <th style="text-align: center;">Contácto</th>
                        <th style="text-align: center;">Teléfono</th>
                        {% get_PermisoUsuario request.user.id "proveedores.change_proveedores" as Permiso %}
                        {% if Permiso %}
                            <th style="text-align: center;">
                                <a href="#" title="Haga clic sobre el icono para editar la fila."><i class='fa fa-info text-white'></i></a>
                            </th>
                        {% endif %}
                        {% comment %} <th style="text-align: center;">
                            <a href="#" title="Haga clic sobre el icono para eliminar la fila."><i class='fa fa-info'></i></a>
                        </th> {% endcomment %}
                    </tr>
                </thead>
                <tbody>
                    {% for linea in page_obj %}
                        <tr>
                            <td style="text-align: center;">{{ linea.nombre }}</td>
                            <td style="text-align: center;">{{ linea.identificacion }}</td>
                            <td style="text-align: center;">{{ linea.email }}</td>
                            <td style="text-align: center;">{{ linea.contacto }}</td>
                            <td style="text-align: center;">{{ linea.telefono }}</td>
                            {% get_PermisoUsuario request.user.id "proveedores.change_proveedores" as Permiso %}
                            {% if Permiso %}
                                <td style="text-align: center;"><a href="{% url 'Proveedores:Edit' pk=linea.id %}" class="btn btn-primary"><i class="fas fa-pencil-alt fa-lg"></i> Editar</a></td>
                            {% endif %}
                            {% comment %} <td style="text-align: center;"><a href="{% url 'Proveedores:Delete' pk=linea.id %}" class="btn btn-danger"><i class="far fa-trash-alt"></i> Borrar</a></td> {% endcomment %}
                        </tr>
                    {% endfor%}
                </tbody>
            </table>

            {% if is_paginated %}
                <div class="d-flex justify-content-center">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination">
                            {% if page_obj.has_previous %}
                                {% if 'nombre' in request.GET %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page=1&name={{ request.GET.name }}">Primera</a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&name={{ request.GET.name }}"><</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page=1">Primera</a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><</a></li>
                                {% endif %}
                            {% endif %}

                            {% for i in page_obj.paginator.page_range %}
                                
                                <li class="page-item">
                                    {% if request.GET.page|to_int == i|to_int %}
                                        {% if 'nombre' in request.GET %}
                                            <a class="page-link page-selected" href="?page={{ i }}&name={{ request.GET.name }}">{{ i }}</a>
                                        {% else %}
                                            <a class="page-link page-selected" href="?page={{ i }}">{{ i }}</a>
                                        {% endif %}
                                    {% else %}
                                        {% if 'nombre' in request.GET %}
                                            <a class="page-link" href="?page={{ i }}&name={{ request.GET.name }}">{{ i }}</a>
                                        {% else %}
                                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                                        {% endif %}
                                    {% endif %}
                                </li>
                            {% endfor %}

                            {% if page_obj.has_next %}
                                {% if 'nombre' in request.GET %}
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.next_page_number }}&name={{ request.GET.name }}">></a>
                                    </li>
                                    <li class="page-item">
                                        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&name={{ request.GET.name }}">Última</a>
                                    </li>
                                {% else %}
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">></a></li>
                                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Última</a></li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            {% endif %}

        {% endif %}
    </div>

    <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="{% url 'Proveedores:Search' %}" id="formSearchName" method="get" enctype="multipart/form-data" class="row ">
                        <div class="form-group col-md-12"> {% comment %} nombre {% endcomment %}
                            <label for="id_nombre">Nombre:</label>
                            {% if 'nombre' in request.GET %}
                                <input type="text" name="nombre" id="id_nombre" class="form-control" placeholder="Nombre" maxlength="100" required="" value="{{request.GET.nombre}}">
                            {% else %}
                                <input type="text" name="nombre" id="id_nombre" class="form-control" placeholder="Nombre" maxlength="100" required="">
                            {% endif %}
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-light">
                                <i class="fas fa-search text-info"></i> Buscar por nombre
                            </button>
                        </div>
                    </form>

                    <form action="{% url 'Proveedores:Search' %}" id="formSearchIdentity" method="get" enctype="multipart/form-data" class="row ">
                        <div class="form-group col-md-12"> {% comment %} identificacion {% endcomment %}
                            <label for="id_nombre">Identificación:</label>
                            {% if 'identificacion' in request.GET %}
                                <input type="text" name="identificacion" id="id_identificacion" class="form-control" placeholder="Identificación" maxlength="100" required="" value="{{request.GET.identificacion}}">
                            {% else %}
                                <input type="text" name="identificacion" id="id_identificacion" class="form-control" placeholder="Identificación" maxlength="100" required="">
                            {% endif %}
                        </div>
                        <div class="col-md-12 text-right">
                            <button type="submit" class="btn btn-light">
                                <i class="fas fa-search text-info"></i> Buscar por identificación
                            </button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block customJs %}
    <script src="{% static 'proveedores/assets/js/validar.js' %}"></script>
    <script>
        {% if 'created' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha creado el proveedor",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}
    </script>
{% endblock %}