bodegas/urls.py
from django.urls import path
from django.views.generic import RedirectView
from bodegas import views as modelViews

bodegas_patterns = ([
    path('',                modelViews.baseListView.as_view(),  name="Base"),
    path('add',             modelViews.CreateView.as_view(),    name="Add"),
    path('edit/<int:pk>',   modelViews.UpdateView.as_view(),    name="Edit"),
    path('del/<int:pk>',    modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',          modelViews.Search,                  name='Search'),
    path('export',          modelViews.exportExcel,             name="exportExcel"),
], "Bodegas")

inventariosBase/urls.py
from django.contrib import admin
from django.urls import path, include

from codeBackEnd.urls import codeBackEnd_patterns
from inventarios.urls import inventarios_patterns
from categorias.urls import categorias_patterns
from bodegas.urls import bodegas_patterns
from proveedores.urls import proveedores_patterns
from transaccionesInventarios.urls import transaccionesInv_patterns
from usuarios.urls import usuarios_patterns

urlpatterns = [
    path('DJAdmin/', admin.site.urls),

    # Paths del auth
    path('', include('django.contrib.auth.urls')),

    # Paths de Admin
    path('', include(codeBackEnd_patterns)),
    path('usuarios/',        include(usuarios_patterns)),

    path('inventarios/',        include(inventarios_patterns)),
    path('categorias/',         include(categorias_patterns)),
    path('bodegas/',            include(bodegas_patterns)),
    path('proveedores/',        include(proveedores_patterns)),
    path('transaccionesInv/',   include(transaccionesInv_patterns)),
]

usuarios/urls.py
from django.urls import path
from django.views.generic import RedirectView
from usuarios import views as modelViews

usuarios_patterns = ([
    path('',                    modelViews.baseListView.as_view(),  name="Base"),
    path('add',                 modelViews.addUsuario,              name="Add"),
    path('addUser',             modelViews.addPostUsuario,          name="AddUser"),
    path('edit/<int:pk>',       modelViews.updateUsuario,           name="Edit"),
    path('edit/update/<int:pk>',modelViews.editUsuario,             name="Update"),
    path('edit/pass/<int:pk>',  modelViews.editUsuarioPass,         name="UpdatePass"),
    path('del/<int:pk>',        modelViews.DeleteView.as_view(),    name="Delete"),
    path('search',              modelViews.Search,                  name='Search'),
    path('export',              modelViews.exportExcel,             name="exportExcel"),
], "Usuarios")

bodegas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bodegas(models.Model):
    nombre          = models.CharField(max_length=100, verbose_name="Nombre")
    responsable     = models.ForeignKey(User, verbose_name="Responsable de la bodega", on_delete=models.DO_NOTHING)
    observacion     = models.CharField(max_length=155, verbose_name="Observación", default="No indicado")

    def __str__(self):
        return self.nombre

usuarios/models.py
from logging import RootLogger
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Perfil(models.Model):
    usuario         = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Usuario")

usuarios/forms.py
from django import forms
from .models import Perfil

class BaseForm(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = [
            'usuario',
        ]

        widgets = {
            'usuario'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
        }

class FormEdit(forms.ModelForm):
    class Meta:
        model = Perfil
        fields = [
            'usuario',
        ]

        widgets = {
            'usuario'        : forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
        }

usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User
from .forms import BaseForm, FormEdit
from codeBackEnd.funciones import estructuraExcel

# Create your views here.
class baseListView(ListView):
    model = User
    template_name = 'usuarios/List.html'
    paginate_by = 30

    ordering = ['-first_name']

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'auth.view_user'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('codeBackEnd:dashboard')

class DeleteView(DeleteView):
    model = User
    template_name = 'usuarios/Del.html'
    success_url = reverse_lazy('Usuarios:Base')

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated == False:
            return redirect('login')
        else:
            if consultar_PermisoUsuario(request, 'auth.delete_user'):
                return super().dispatch(request, *args, *kwargs)
            else:
                return redirect('Usuarios:Base')

def addUsuario(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.add_user'):
            datos = {}
            return render(request, "usuarios/Add.html", datos)
        else:
            return redirect('Usuarios:Base')
    else:
        return redirect('login')

def addPostUsuario(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.add_user'):
            if request.method == "POST":
                if request.POST['pass'] == request.POST['confPass']:
                    usuario = User.objects.create_user(request.POST['usuario'], request.POST['correo'], request.POST['pass'])
                    
                    usuario.first_name = request.POST['nombre']
                    usuario.last_name = request.POST['apellido']
                    usuario.save()
                    datos = {}

                    return redirect('Usuarios:Base')
                else:
                    datos = {}
                    return render(request, "usuarios/Add.html", datos)
            else:
                datos = {}
                return render(request, "usuarios/Add.html", datos)
        else:
            return redirect('Usuarios:Base')
    else:
        return redirect('login')

def updateUsuario(request, pk):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.change_user'):
            usuario = User.objects.filter(id=pk)[0]

            datos = {
                'usuario':usuario,
            }

            return render(request, "usuarios/Edit.html", datos)
        else:
            return redirect('Usuarios:Base')
    else:
        return redirect('login')

def editUsuario(request, pk):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.change_user'):
            if request.method == "POST":
                usuario = User.objects.filter(id=pk)[0]

                usuario.first_name = request.POST['nombre']
                usuario.last_name = request.POST['apellido']
                usuario.save()

                base_url = reverse('Usuarios:Edit', kwargs={'pk':pk})
                query_string =  'ok_perfil'
                url = '{}?{}'.format(base_url, query_string)

                return redirect(url)
            else:
                base_url = reverse('Usuarios:Edit', kwargs={'pk':pk})
                query_string =  'error'
                url = '{}?{}'.format(base_url, query_string)
                return redirect(url)
        else:
            return redirect('Usuarios:Base')
        
    else:
        return redirect('login')

def editUsuarioPass(request, pk):
    ReturnRequest = reverse('Usuarios:Edit', kwargs={'pk':pk})
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.change_user'):
            if request.method == "POST":
                if (request.POST['pass'] != '' and request.POST['confPass'] != '') and (request.POST['pass'] == request.POST['confPass']):
                    usuario = User.objects.filter(id=pk)[0]
                    usuario.set_password(request.POST['pass'])
                    usuario.save()

                    base_url = ReturnRequest
                    query_string =  'ok_pass'
                    url = '{}?{}'.format(base_url, query_string)

                    return redirect(url)
                else:
                    base_url = ReturnRequest
                    query_string =  'error'
                    url = '{}?{}'.format(base_url, query_string)

                    return redirect(url)
            else:
                return redirect('Usuarios:Base')
        else:
            base_url = ReturnRequest
            query_string =  'error'
            url = '{}?{}'.format(base_url, query_string)

            return redirect(url)
    else:
        return redirect('login')

def Search(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'auth.view_user'):
            filtroTipoFiltro = request.GET.get('tipoFiltro', '')
            filtroNombre = request.GET.get('nombre', '')
            filtroEmail = request.GET.get('email', '')

            # trae los User relacionados
            filtro_list = []

            if (filtroTipoFiltro != '' and filtroTipoFiltro != None) and (filtroNombre != '' and filtroNombre != None):
                if filtroTipoFiltro == "1":
                    filtro_list = User.objects.filter(first_name__icontains=filtroNombre)
                elif filtroTipoFiltro == "2":
                    filtro_list = User.objects.filter(last_name__icontains=filtroNombre)
            elif filtroEmail != '' and filtroEmail != None:
                filtro_list = User.objects.filter(email__icontains=filtroEmail)
            else:
                return redirect(reverse_lazy('Usuarios:Base'))

            page = request.GET.get('page', 1)
            paginator = Paginator(filtro_list, 30)

            try:
                usuarios = paginator.page(page)
            except PageNotAnInteger:
                usuarios = paginator.page(1)
            except EmptyPage:
                usuarios = paginator.page(paginator.num_pages)

            datos = {
                'is_paginated':  True if paginator.num_pages > 1 else False,
                'page_obj': usuarios,
            }

            return render(request, "usuarios/List.html", datos)
        else:
            return redirect('codeBackEnd:dashboard')
    else:
        return redirect('login')

def consultar_PermisoUsuario(request, permiso):
    all_permissions_in_groups = request.user.get_group_permissions()

    tienePermiso = False
    for permisoGrupo in all_permissions_in_groups:
        if permisoGrupo == permiso:
            tienePermiso = True

    return tienePermiso

def exportExcel(request):
    if request.user.is_authenticated:
        if consultar_PermisoUsuario(request, 'transaccionesInventarios.view_transacciones'):
            filtroTipoFiltro = request.GET.get('tipoFiltro', '')
            filtroNombre = request.GET.get('nombre', '')
            filtroEmail = request.GET.get('email', '')

            # trae los User relacionados
            filtro_list = []

            if (filtroTipoFiltro != '' and filtroTipoFiltro != None) and (filtroNombre != '' and filtroNombre != None):
                if filtroTipoFiltro == "1":
                    filtro_list = User.objects.filter(first_name__icontains=filtroNombre)
                elif filtroTipoFiltro == "2":
                    filtro_list = User.objects.filter(last_name__icontains=filtroNombre)
            elif filtroEmail != '' and filtroEmail != None:
                filtro_list = User.objects.filter(email__icontains=filtroEmail)
            else:
                filtro_list = User.objects.all()

            datosExcel = []

            for usuario in filtro_list:
                linea = [[
                    usuario.id,
                    usuario.first_name,
                    usuario.last_name,
                    usuario.username,
                    usuario.email,
                ]]
                datosExcel = datosExcel + linea

            titulos = [[
                "N. Usuario",
                "Nombre",
                "Apellidos",
                "Usuario",
                "Correo electrónico",
            ],]

            excelExportar = estructuraExcel(titulos, datosExcel, 'usuarios')

            # return the response
            return excelExportar
        else:
            return redirect('codeBackEnd:dashboard')

    else:
        return redirect('login')

usuarios/templates/usuarios/Add.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% block title %}Nuevo usuario{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/check-list.png' %}"> Nuevo usuario{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style></style>
{% endblock %}

{% block content %}
    <form action="{% url 'Usuarios:AddUser' %}" id="formAdd" method="post" enctype="multipart/form-data" class="row ">
        {% csrf_token %}

        <div class="form-group col-md-6">
            <label for="id_nombre">Nombre</label>
            <input type="text" id="id_nombre" class="form-control" placeholder="Nombre" maxlength="200" name="nombre">
        </div>

        <div class="form-group col-md-6">
            <label for="id_apellido">Apellido</label>
            <input type="text" id="id_apellido" class="form-control" placeholder="Apellido" maxlength="200" name="apellido">
        </div>

        <div class="form-group col-md-6">
            <label for="url">Usuario</label>
            <input type="text" id="id_usuario" class="form-control" placeholder="Usuario" maxlength="200" name="usuario">
        </div>

        <div class="form-group col-md-6">
            <label for="id_correo">Correo electrónico</label>
            <input type="text" id="id_correo" class="form-control" placeholder="Correo" maxlength="200" name="correo">
        </div>

        <div class="form-group col-md-6">
            <label for="url">Contraseña</label>
            <input type="password" id="id_pass" class="form-control" placeholder="Nueva contraseña" maxlength="60" name="pass" >
        </div>

        <div class="form-group col-md-6">
            <label for="id_correo">Confirmar contraseña</label>
            <input type="password" id="id_confPass" class="form-control" placeholder="Confirmar contraseña" maxlength="60" name="confPass" >
        </div>

        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Usuarios:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0">
                    <button type="submit" class="btn btn-light">
                        <i class="far fa-save"></i> Guardar usuario
                    </button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

{% block customJs %}
    <script src="{% static 'usuarios/assets/js/validar.js' %}"></script>
{% endblock %}

usuarios/templates/usuarios/Del.html
{% extends 'codeBackEnd/base.html' %}
{% load humanize %}
{% load static %}
{% block title %}Borrar categoría{% endblock %}
{% block tituloSeccion %}<img class="img-titulo" src="{% static 'codeBackEnd/admin/img/png/check-list.png' %}"> Borrar categoría{% endblock %}

{% block customHead %}
    <link href="{% static 'codeBackEnd/admin/assets/dataTables/css/dataTables.bootstrap4.css' %}" rel="stylesheet"  type="text/css"/>
{% endblock %}

{% block customCss %}
    <style>
        tbody tr td{ color: #ffffff; }
        tbody tr td a{ color: #5C9FF1; padding-left: 10px; }
        .estado .alert{
            background-color: rgba(255,255,255,.05);
            margin-top: 10px;
            padding: .8rem 1rem;
        }
    </style>
{% endblock %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <h2 class="text-white">¿Estás seguro de que quieres borrar "<b>{{ object }}</b>"?</h2>
        <input type="submit"  class="btn btn-danger float-right" value="Sí, borrar" />
    </form>
{% endblock %}

usuarios/templates/usuarios/Edit.html
{% extends 'codeBackEnd/base.html' %}
{% load static %}
{% block title %}Editar usuario{% endblock %}
{% block tituloSeccion %}Editar usuario{% endblock %}

{% block customCss %}
    <style>
        .nav-link {
            color: #4a5568;
        }

        .gutters-sm {
            margin-right: -8px;
            margin-left: -8px;
        }

        .gutters-sm>.col, .gutters-sm>[class*=col-] {
            padding-right: 8px;
            padding-left: 8px;
        }
        .mb-3, .my-3 {
            margin-bottom: 1rem!important;
        }

        .bg-gray-300 {
            background-color: #e2e8f0;
        }
        .h-100 {
            height: 100%!important;
        }
        .shadow-none {
            box-shadow: none!important;
        }

        .tab-config a.active, .tab-config a:hover{
            background: #011128 !important;
            color: #fff !important;
            border: 1px #011128 !important;
            border-radius: 0px !important;
        }
        
        .tab-config a.active .svg-menu, .tab-config a:hover .svg-menu{
            filter: invert(100%) sepia(100%) saturate(0%) hue-rotate(288deg) brightness(102%) contrast(102%);
        }

        .tab-config a {
            background: #fff !important;
            color: #011128 !important;
            border: 1px #fff !important;
            border-radius: 0px !important;
        }

        .tab-config-lateral a{
            text-align: left !important;
            padding-left: 15px !important;
        }
    </style>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row gutters-sm">
            <div class="col-md-4 d-none d-md-block">
                <div class="card">
                    <div class="card-body">
                        <nav class="nav flex-column nav-pills nav-gap-y-1 tab-config tab-config-lateral">
                            <a href="#profile" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded active">
                                <img src="{% static 'codeBackEnd/admin/img/svg/user-blue.svg' %}" class="svg-menu" style="width: 40px; margin-right: 15px;">
                                Información
                            </a>
                            <a href="#security" data-toggle="tab" class="nav-item nav-link has-icon nav-link-faded">
                                <img src="{% static 'codeBackEnd/admin/img/svg/secure-shield.svg' %}" class="svg-menu" style="width: 40px; margin-right: 15px;">
                                Seguridad
                            </a>
                        </nav>
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header border-bottom mb-3 d-flex d-md-none" style="padding: 1rem 0.6rem; border: 0px !important;">
                        <ul class="nav nav-tabs card-header-tabs nav-gap-x-1 tab-config" role="tablist">
                            <li class="nav-item">
                                <a href="#profile" data-toggle="tab" class="nav-link has-icon active">
                                    <img src="{% static 'codeBackEnd/admin/img/svg/user-blue.svg' %}" class="svg-menu" style="width: 40px;">
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#security" data-toggle="tab" class="nav-link has-icon">
                                    <img src="{% static 'codeBackEnd/admin/img/svg/secure-shield.svg' %}" class="svg-menu" style="width: 40px;">
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="card-body tab-content" style="background: rgba(255,255,255,.07);">
                        <div class="tab-pane active" id="profile">
                            <h6 class="text-white">INFORMACIÓN DE PERFIL</h6>
                            <hr>
                            <form action="{% url 'Usuarios:Update' pk=usuario.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="fullName">Nombre</label>
                                    <input type="text" id="idnombre" class="form-control" placeholder="Nombre" maxlength="200" value="{{usuario.first_name}}" name="nombre">
                                </div>

                                <div class="form-group">
                                    <label for="bio">Apellido</label>
                                    <input type="text" id="idapellido" class="form-control" placeholder="Apellido" maxlength="200" value="{{usuario.last_name}}" name="apellido">
                                </div>

                                <div class="form-group">
                                    <label for="url">Usuario</label>
                                    <input type="text" class="form-control" value="{{usuario.username}}" readonly>
                                </div>

                                <div class="form-group">
                                    <label for="location">Correo electrónico</label>
                                    <input type="text" class="form-control" value="{{usuario.email}}" readonly>
                                </div>

                                <div class="form-group small text-warning">
                                    El usuario y correo electrónico no pueden ser modificados
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Actualizar</button>
                                </div>

                            </form>
                        </div>

                        <div class="tab-pane" id="security">
                            <h6 class="text-white">CONFIGURACIONES DE SEGURIDAD</h6>
                            <hr>
                            <form action="{% url 'Usuarios:UpdatePass' pk=usuario.id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="fullName">Nueva contraseña:</label>
                                    <input type="password" id="idpass" class="form-control" placeholder="Nueva contraseña" maxlength="60" name="pass" >
                                </div>

                                <div class="form-group">
                                    <label for="bio">Confirmar contraseña:</label>
                                    <input type="password" id="idconfPass" class="form-control" placeholder="Confirmar contraseña" maxlength="60" name="confPass" >
                                </div>
                                <div class="form-group small text-warning">
                                    Guarda la nueva contraseña en un lugar seguro
                                </div>

                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Actualizar</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="form-group col-md-12 pr-0">
            <div class="row col-md-12 pr-0">
                <div class="text-center col-12 order-2 text-sm-left order-sm-1 col-sm-6 p-sm-0">
                    <a href="{% url 'Usuarios:Base' %}" type="button" class="btn btn-light"><i class="fas fa-chevron-left"></i> Volver al listado</a>
                </div>
                <div class="text-center col-12 mb-2 order-1 text-sm-right order-sm-2 mb-sm-0 col-sm-6 p-sm-0"></div>
            </div>
        </div>
    </div>

{% endblock %}

{% block customJs %}
    <script>
        {% if 'ok_perfil' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha actualizado el usuario",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}

        {% if 'ok_pass' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha actualizado la contraseña",
                icon: "success",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-success",
                        closeModal: true
                    }
                }
            });
        {% endif %}

        {% if 'error' in request.GET %}
            swal({
                title: "Realizado",
                text: "Se ha actualizado la contraseña",
                icon: "error",
                buttons: {
                    confirm: {
                        text: "OK",
                        value: true,
                        visible: true,
                        className: "btn btn-danger",
                        closeModal: true
                    }
                }
            });
        {% endif %}

    </script>
{% endblock %}